#pragma once

#define DARK_KEY_0                  48
#define DARK_KEY_1                  49
#define DARK_KEY_2                  50
#define DARK_KEY_3                  51
#define DARK_KEY_4                  52
#define DARK_KEY_5                  53
#define DARK_KEY_6                  54
#define DARK_KEY_7                  55
#define DARK_KEY_8                  56
#define DARK_KEY_9                  57
#define DARK_KEY_SEMICOLON          59  /* ; */
#define DARK_KEY_EQUAL              61  /* = */
#define DARK_KEY_A                  65
#define DARK_KEY_B                  66
#define DARK_KEY_C                  67
#define DARK_KEY_D                  68
#define DARK_KEY_E                  69
#define DARK_KEY_F                  70
#define DARK_KEY_G                  71
#define DARK_KEY_H                  72
#define DARK_KEY_I                  73
#define DARK_KEY_J                  74
#define DARK_KEY_K                  75
#define DARK_KEY_L                  76
#define DARK_KEY_M                  77
#define DARK_KEY_N                  78
#define DARK_KEY_O                  79
#define DARK_KEY_P                  80
#define DARK_KEY_Q                  81
#define DARK_KEY_R                  82
#define DARK_KEY_S                  83
#define DARK_KEY_T                  84
#define DARK_KEY_U                  85
#define DARK_KEY_V                  86
#define DARK_KEY_W                  87
#define DARK_KEY_X                  88
#define DARK_KEY_Y                  89
#define DARK_KEY_Z                  90
#define DARK_KEY_LEFT_BRACKET       91  /* [ */
#define DARK_KEY_BACKSLASH          92  /* \ */
#define DARK_KEY_RIGHT_BRACKET      93  /* ] */
#define DARK_KEY_GRAVE_ACCENT       96  /* ` */

#define DARK_KEY_ESCAPE             256
#define DARK_KEY_ENTER              257
#define DARK_KEY_TAB                258
#define DARK_KEY_BACKSPACE          259
#define DARK_KEY_INSERT             260
#define DARK_KEY_DELETE             261
#define DARK_KEY_RIGHT              262
#define DARK_KEY_LEFT               263
#define DARK_KEY_DOWN               264
#define DARK_KEY_UP                 265
#define DARK_KEY_PAGE_UP            266
#define DARK_KEY_PAGE_DOWN          267
#define DARK_KEY_HOME               268
#define DARK_KEY_END                269
#define DARK_KEY_CAPS_LOCK          280
#define DARK_KEY_SCROLL_LOCK        281
#define DARK_KEY_NUM_LOCK           282
#define DARK_KEY_PRINT_SCREEN       283
#define DARK_KEY_PAUSE              284
#define DARK_KEY_F1                 290
#define DARK_KEY_F2                 291
#define DARK_KEY_F3                 292
#define DARK_KEY_F4                 293
#define DARK_KEY_F5                 294
#define DARK_KEY_F6                 295
#define DARK_KEY_F7                 296
#define DARK_KEY_F8                 297
#define DARK_KEY_F9                 298
#define DARK_KEY_F10                299
#define DARK_KEY_F11                300
#define DARK_KEY_F12                301
#define DARK_KEY_F13                302
#define DARK_KEY_F14                303
#define DARK_KEY_F15                304
#define DARK_KEY_F16                305
#define DARK_KEY_F17                306
#define DARK_KEY_F18                307
#define DARK_KEY_F19                308
#define DARK_KEY_F20                309
#define DARK_KEY_F21                310
#define DARK_KEY_F22                311
#define DARK_KEY_F23                312
#define DARK_KEY_F24                313
#define DARK_KEY_F25                314
#define DARK_KEY_KP_0               320
#define DARK_KEY_KP_1               321
#define DARK_KEY_KP_2               322
#define DARK_KEY_KP_3               323
#define DARK_KEY_KP_4               324
#define DARK_KEY_KP_5               325
#define DARK_KEY_KP_6               326
#define DARK_KEY_KP_7               327
#define DARK_KEY_KP_8               328
#define DARK_KEY_KP_9               329
#define DARK_KEY_KP_DECIMAL         330
#define DARK_KEY_KP_DIVIDE          331
#define DARK_KEY_KP_MULTIPLY        332
#define DARK_KEY_KP_SUBTRACT        333
#define DARK_KEY_KP_ADD             334
#define DARK_KEY_KP_ENTER           335
#define DARK_KEY_KP_EQUAL           336
#define DARK_KEY_LEFT_SHIFT         340
#define DARK_KEY_LEFT_CONTROL       341
#define DARK_KEY_LEFT_ALT           342
#define DARK_KEY_LEFT_SUPER         343
#define DARK_KEY_RIGHT_SHIFT        344
#define DARK_KEY_RIGHT_CONTROL      345
#define DARK_KEY_RIGHT_ALT          346
#define DARK_KEY_RIGHT_SUPER        347
#define DARK_KEY_MENU               348

#define DARK_MOUSE_BUTTON_1         0
#define DARK_MOUSE_BUTTON_2         1
#define DARK_MOUSE_BUTTON_3         2
#define DARK_MOUSE_BUTTON_4         3
#define DARK_MOUSE_BUTTON_5         4
#define DARK_MOUSE_BUTTON_6         5
#define DARK_MOUSE_BUTTON_7         6
#define DARK_MOUSE_BUTTON_8         7
#define DARK_MOUSE_BUTTON_LAST      GLFW_MOUSE_BUTTON_8
#define DARK_MOUSE_BUTTON_LEFT      GLFW_MOUSE_BUTTON_1
#define DARK_MOUSE_BUTTON_RIGHT     GLFW_MOUSE_BUTTON_2
#define DARK_MOUSE_BUTTON_MIDDLE    GLFW_MOUSE_BUTTON_3

#define DARK_RELEASE                0
#define DARK_PRESS                  1
#define DARK_REPEAT                 2